name: zubisdyn
description: Social media app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # plugins
  firebase_core: ^1.0.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.3
  
  # flutter
  flutter_redux: ^0.7.0


  # dart
  built_value: ^8.0.2
  built_collection: ^5.0.0
  redux: ^5.0.0

  # packages
  redux_epics: ^0.14.0
  freezed_annotation: ^0.12.0
  meta: ^1.3.0


dev_dependencies:
  build_runner: ^1.11.5
  built_value_generator: ^8.0.2
  flutter_test:
    sdk: flutter
  freezed: ^0.12.2
  mockito: ^5.0.0
  lcov: ^6.0.0
  
dependency_overrides:
  rxdart: ^0.26.0
  redux: ^5.0.0
  analyzer: ^1.1.0
  http: ^0.13.0
  plugin_platform_interface: ^2.0.0


flutter:
  uses-material-design: true
