name: zubisdyn
description: Social media app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # plugins
  firebase_core: ^1.13.1
  cupertino_icons: ^1.0.4
  firebase_auth: ^3.3.10
  cloud_firestore: ^3.1.10
  cloud_functions: ^3.2.10
  firebase_storage: ^10.2.9
  image_picker: ^0.8.4+11
  photo_manager: ^2.0.1
  photo_view: ^0.13.0
  
  # flutter
  flutter_redux: ^0.8.2
  loading_overlay: ^0.3.0

  # dart
  built_value: ^8.1.4
  built_collection: ^5.1.1
  redux: ^5.0.0
  email_validator: ^2.0.1
  grpc: ^3.0.2
  protobuf: ^2.0.1
  dotted_border: ^2.0.0+2
  uuid: ^3.0.6
  
  # packages
  redux_epics: ^0.15.1
  freezed_annotation: ^1.1.0
  meta: ^1.7.0


dev_dependencies:
  build_runner: ^2.1.8
  built_value_generator: ^8.1.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  mockito: ^5.1.0
  # lcov: ^6.0.0

dependency_overrides:
  rxdart: ^0.26.0
  redux: ^5.0.0
  analyzer: ^3.3.1
  http: ^0.13.0
  plugin_platform_interface: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - res/icons/
    - res/images/
